# -*- coding: utf-8 -*-
"""
help_texts
----------
Справки инструментов на русском и английском.

Вынесены из кода алгоритмов по двум причинам. Тексты длинные, и внутри
классов они мешали читать логику. И перевод целого абзаца надёжнее перевода
россыпи коротких строк: смысл сохраняется, а словарь не отстаёт от кода
незаметно.

Ключ это имя алгоритма, то же, что возвращает метод name.
"""

try:  # внутри плагина QGIS
    from .i18n import is_russian
except ImportError:  # headless-тесты
    from i18n import is_russian

__all__ = ["help_for"]


def help_for(name):
    """Справка инструмента на языке интерфейса."""
    table = RU if is_russian() else EN
    return table.get(name, RU.get(name, ""))


# ────────────────────────────────────────────────────────────────────────────
# Русский
# ────────────────────────────────────────────────────────────────────────────

RU = {

"topologyaudit": (
    "<b>1.01 Проверка топологии полигонального слоя</b><br><br>"
    "Слой не изменяется. Результат это слой точек с найденными нарушениями "
    "и сводка в панели Processing.<br><br>"
    "<b>Что проверяется</b><br><ul>"
    "<li>некорректная геометрия и самокасания колец.</li>"
    "<li>повторяющиеся вершины и иглы.</li>"
    "<li>вершины, лежащие на ребре соседа без узла, и отдельно вершины, "
    "лишь проходящие рядом с ребром.</li>"
    "<li>микродыры, микрочасти, микрообъекты, волосяные полигоны.</li>"
    "<li>перекрытия, дубликаты, вложенные объекты.</li>"
    "<li>щели в покрытии.</li></ul>"
    "<b>Два уровня</b>. Нарушения делятся по полю <b>severity</b>: "
    "<b>auto</b> означает заведомый мусор, который инструмент очистки исправит "
    "сам, <b>review</b> означает возможный смысл, такое не исправляется "
    "автоматически ни при каких настройках.<br><br>"
    "Границу проводят два порога: допуск в единицах длины и порог площади.<br><br>"
    "<b>Два похожих нарушения стоит различать</b>. "
    "<b>Вершина лежит на ребре соседа</b> означает расстояние ноль: границы "
    "совпадают геометрически, но вершинность у соседей разная. Это дефект при "
    "любом допуске. <b>Вершина рядом с ребром</b> означает лишь близость, "
    "и число таких находок целиком задаётся допуском. Если в сводке медиана "
    "близка к допуску, а не к нулю, вы смотрите на соседние объекты, а не "
    "на дефекты. Первое лечится инструментом <b>1.05</b>, который не трогает "
    "ни форму, ни площадь.<br><br>"
    "<b>Поле группировки</b> нужно, когда слой не является единым покрытием, "
    "например когда зоны нескольких пластов лежат в одном слое. Объекты разных "
    "групп накладываются друг на друга по замыслу.<br><br>"
    "<b>Площадь законной полости</b> отделяет целик, озеро или "
    "незакартированный участок от дефекта покрытия: мелкая дыра это ошибка, "
    "очень крупная почти всегда часть замысла.<br><br>"
    "<b>Ограничение</b>. Щели определяются как дыры в объединении покрытия, "
    "поэтому зазор, выходящий на внешний край покрытия, дырой не считается. "
    "Такие зазоры закрывает сшивка вершин, если их ширина меньше допуска."
),

"topologyfix": (
    "<b>1.02 Очистка топологии в один проход</b><br><br>"
    "Исправляет всё, что заведомо является техническим мусором, и не трогает "
    "то, что может нести смысл. Второе попадает в слой оставшихся проблем.<br><br>"
    "<b>Порядок шагов</b> (он существенен)<br><ol>"
    "<li>снятие повторяющихся вершин и игл.</li>"
    "<li>удаление микрочастей и заливка микродыр.</li>"
    "<li>сшивка: слияние близких вершин и вставка недостающих узлов.</li>"
    "<li>исправление некорректной геометрии с контролем потери площади.</li>"
    "<li>вычитание узких перекрытий по правилу приоритета.</li>"
    "<li>передача мелких щелей соседу с самой длинной общей границей.</li>"
    "</ol>"
    "<b>Чего инструмент не делает никогда</b>: не удаляет объекты с широкими "
    "перекрытиями, не заполняет крупные щели, не разрешает дубликаты "
    "и вложения, не удаляет микрообъекты без явного разрешения.<br><br>"
    "<b>Перекрытие оценивается шириной, а не площадью</b>. Полоса шириной "
    "с допуск и длиной в десятки метров набирает сотню квадратных единиц, "
    "оставаясь следствием смещения вершин, а не спором за площадь.<br><br>"
    "<b>Гарантии</b>. Вершина не смещается дальше допуска. Правка, отнимающая "
    "у объекта больше четверти площади, отменяется. Повторный запуск "
    "по результату ничего не меняет.<br><br>"
    "<b>Отметки Z</b> восстанавливаются по ближайшей исходной вершине, "
    "поскольку операции пересечения работают в плане.<br><br>"
    "Выходной слой всегда составного типа: исправление может разделить объект "
    "на несколько частей.<br><br>"
    "Перед запуском стоит выполнить <b>1.01</b> и посмотреть, сколько нарушений "
    "попадает в разряд решаемых человеком."
),

"topologyclean": (
    "<b>1.03 Топологическая сшивка слоя</b><br><br>"
    "Приводит границы соседних объектов к точному совпадению, не сдвигая "
    "геометрию дальше заданного допуска. Заменяет ручную процедуру снапа слоя "
    "к самому себе со вставкой вершин.<br><br>"
    "<b>Две операции</b><br><ul>"
    "<li><b>Вставка узлов</b>. Если вершина одного объекта лежит на ребре "
    "соседнего, но узла там нет, узел вставляется. Существующие вершины "
    "остаются на месте. Отдельно ставятся узлы там, где рёбра пересекаются "
    "крест-накрест без общих вершин.</li>"
    "<li><b>Слияние вершин</b>. Вершины ближе допуска друг к другу сводятся "
    "в одну точку. Порядок обхода задаёт, кто кого притягивает: лидер кластера "
    "не двигается.</li></ul>"
    "<b>Гарантия</b>. Ни одна вершина не смещается дальше допуска. "
    "Кластеризация жадная по лидеру, поэтому цепочек из вершин, уводящих "
    "геометрию за допуск, не возникает.<br><br>"
    "<b>Объекты уже допуска</b> при слиянии схлопнулись бы сами в себя: "
    "их противоположные берега слиплись бы. По умолчанию такие объекты "
    "остаются нетронутыми и служат опорой для соседей.<br><br>"
    "<b>Эталонный слой</b> (необязательно). Его вершины считаются неподвижными "
    "и притягивают входной слой. Сам эталон не изменяется и в результат "
    "не попадает.<br><br>"
    "<b>Отметки Z</b> сохраняются. При слиянии вершина берёт плановые "
    "координаты лидера и оставляет собственную отметку.<br><br>"
    "Повторный запуск по готовому результату ничего не меняет."
),

"assemblycheck": (
    "<b>1.04 Контроль сборки по атрибуту</b><br><br>"
    "Проверяет, собирается ли каждая группа объектов в одно целое тело. "
    "Объединение объектов с одинаковым значением атрибута должно давать ровно "
    "одну часть без внутренних колец.<br><br>"
    "<b>Зачем это нужно</b>. Именно ради корректной сборки блоков и панелей "
    "покрытие и приводится в порядок. Проверка отвечает на конечный вопрос "
    "напрямую, вместо ручного объединения без атрибутов с разглядыванием "
    "результата.<br><br>"
    "<b>Что находится</b><br><ul>"
    "<li><b>Группа распалась на части</b>. Внутри группы остался разрыв. "
    "В поле <b>note</b> указано расстояние до ближайшей части: это и есть "
    "допуск, которого не хватило.</li>"
    "<li><b>Внутреннее кольцо в группе</b>. Внутри группы осталась дыра. "
    "Настоящие технологические полости тоже попадут сюда, их отличают "
    "по площади.</li></ul>"
    "<b>Важное свойство</b>. Проверка находит то, чего не видит поиск щелей "
    "по всему покрытию. Зазор, выходящий на внешний край, дырой в объединении "
    "не является, но при сборке группы он разрезает её на части.<br><br>"
    "<b>Когда группа не обязана быть цельной</b>. Одно значение атрибута часто "
    "описывает несколько разнесённых тел: полигоны изолиний одного уровня, "
    "участки одного типа, острова. Для таких данных задайте <b>максимальный "
    "разрыв</b>: части, отстоящие дальше него, считаются законно отдельными "
    "телами. Признак того, что порог нужен, виден сразу: если в поле note "
    "стоят сотни метров, это не дефекты сборки.<br><br>"
    "Если выбрано несколько полей, ключом становится их сочетание."
),

"insertnodes": (
    "<b>1.05 Вставка недостающих узлов</b><br><br>"
    "Достраивает узлы там, где вершина одного объекта лежит на ребре другого, "
    "но узла там нет. Ничего больше инструмент не делает: существующие вершины "
    "не двигаются и не удаляются.<br><br>"
    "<b>Когда это нужно</b>. Границы соседей совпадают геометрически, "
    "а вершинность у них разная. Отрисовке это не мешает и на глаз не видно, "
    "но мешает объединению по атрибуту, оверлеям, генерализации и загрузке "
    "в базу со строгой топологией. Типичный источник это независимое построение "
    "полигонов по разные стороны общей прямой, например линии разлома "
    "или края маски обрезки.<br><br>"
    "<b>Гарантия</b>. Узел ставится в проекцию точки на ребро, то есть строго "
    "на прямую этого ребра. Поэтому форма не меняется вовсе, и появиться "
    "самопересечению неоткуда. Отчёт печатает площадь до и после: расхождение "
    "возможно только на уровне точности координат.<br><br>"
    "<b>Проходов может понадобиться несколько</b>: вставленный узел сам иногда "
    "ложится на ребро третьего объекта. Инструмент повторяет проходы, пока узлы "
    "находятся, и печатает их число.<br><br>"
    "<b>Опорный слой</b> (необязательно). Его вершины служат источником узлов "
    "для входного слоя. Сам он не изменяется и в результат не попадает.<br><br>"
    "<b>Отклонение от ребра</b> это не допуск в обычном смысле. Здесь "
    "расстояние равно нулю, и число нужно лишь как защита. Умолчание отвечает "
    "точности координат, а не размеру объектов. Увеличивать его до метров "
    "не следует: инструмент начнёт подтягивать рёбра, и обещание про площадь "
    "перестанет выполняться.<br><br>"
    "Находит эти места инструмент <b>1.01</b>, тип нарушения <b>вершина лежит "
    "на ребре соседа без узла</b>."
),

"topologysimplify": (
    "<b>2.01 Упрощение с сохранением общих границ</b><br><br>"
    "Прореживает вершины так, что граница, общая для двух соседей, остаётся "
    "общей.<br><br>"
    "<b>Зачем это нужно</b>. Обычное упрощение обрабатывает каждый полигон "
    "отдельно, поэтому одна и та же граница прореживается дважды и по-разному: "
    "там, где была одна линия, появляются щели и перехлёсты. На слое зон "
    "из 341 объекта независимое упрощение с допуском 5 давало 46 перекрытий "
    "и 25 щелей, топологическое не даёт ни одного.<br><br>"
    "<b>Как это работает</b><br><ul>"
    "<li>Кольца раскладываются на рёбра, ребро опознаётся по паре концов "
    "без учёта направления. Поэтому одно и то же ребро у двух соседей даёт "
    "одну запись.</li>"
    "<li>Рёбра склеиваются в дуги. Дуга обрывается там, где сходятся три "
    "полигона или меняется набор владельцев границы.</li>"
    "<li>Каждая дуга прореживается ровно один раз, и обоим соседям достаётся "
    "один и тот же результат.</li>"
    "<li>Концы дуг неподвижны, поэтому узлы, где сходятся три полигона, "
    "остаются на месте.</li></ul>"
    "<b>Допуск</b> задаёт предельное отклонение упрощённой линии от исходной, "
    "как в методе Дугласа-Пекера.<br><br>"
    "<b>Точность опознания общих вершин</b> это не допуск упрощения. Она нужна, "
    "когда соседи записаны с разной точностью координат.<br><br>"
    "Площадь при упрощении меняется, это его смысл. Топология при этом "
    "не портится: проверьте результат инструментом <b>1.01</b>, число находок "
    "не должно вырасти."
),

}


# ────────────────────────────────────────────────────────────────────────────
# English
# ────────────────────────────────────────────────────────────────────────────

EN = {

"topologyaudit": (
    "<b>1.01 Topology check for a polygon layer</b><br><br>"
    "The layer is not modified. The result is a point layer with the violations "
    "found, plus a summary in the Processing panel.<br><br>"
    "<b>What is checked</b><br><ul>"
    "<li>invalid geometry and ring self-touches.</li>"
    "<li>repeated vertices and spikes.</li>"
    "<li>vertices lying on a neighbour edge without a node, and separately "
    "vertices that merely pass close to an edge.</li>"
    "<li>tiny holes, tiny parts, tiny objects, sliver polygons.</li>"
    "<li>overlaps, duplicates, nested objects.</li>"
    "<li>gaps in the coverage.</li></ul>"
    "<b>Two levels</b>. Violations are split by the <b>severity</b> field: "
    "<b>auto</b> means certain debris that the cleanup tool will fix by itself, "
    "<b>review</b> means possible meaning, and such cases are never fixed "
    "automatically under any settings.<br><br>"
    "The boundary is drawn by two thresholds: a tolerance in length units "
    "and an area threshold.<br><br>"
    "<b>Two similar violations are worth telling apart</b>. "
    "<b>A vertex lies on a neighbour edge</b> means the distance is zero: "
    "the borders coincide geometrically, but the neighbours have different "
    "vertices. This is a defect under any tolerance. <b>A vertex near an edge</b> "
    "means mere proximity, and the number of such findings is set entirely "
    "by the tolerance. If the median in the summary is close to the tolerance "
    "rather than to zero, you are looking at neighbouring objects, not at "
    "defects. The first case is fixed by tool <b>1.05</b>, which changes "
    "neither shape nor area.<br><br>"
    "<b>The grouping field</b> is needed when the layer is not a single "
    "coverage, for example when zones of several seams share one layer. "
    "Objects of different groups overlap each other by design.<br><br>"
    "<b>The legitimate cavity area</b> separates a pillar, a lake or an "
    "unmapped area from a coverage defect: a small hole is an error, a very "
    "large one is almost always part of the design.<br><br>"
    "<b>Limitation</b>. Gaps are found as holes in the union of the coverage, "
    "so a gap that reaches the outer edge is not a hole. Such gaps are closed "
    "by vertex snapping when their width is below the tolerance."
),

"topologyfix": (
    "<b>1.02 Topology cleanup in a single pass</b><br><br>"
    "Fixes everything that is certainly technical debris and leaves alone "
    "anything that may carry meaning. The latter goes into the layer "
    "of remaining problems.<br><br>"
    "<b>Order of steps</b> (it matters)<br><ol>"
    "<li>removal of repeated vertices and spikes.</li>"
    "<li>removal of tiny parts and filling of tiny holes.</li>"
    "<li>snapping: merging close vertices and inserting missing nodes.</li>"
    "<li>repair of invalid geometry with area loss control.</li>"
    "<li>subtraction of narrow overlaps by the priority rule.</li>"
    "<li>handing small gaps to the neighbour with the longest shared border.</li>"
    "</ol>"
    "<b>What the tool never does</b>: it does not delete objects with wide "
    "overlaps, does not fill large gaps, does not resolve duplicates and nested "
    "objects, and does not delete tiny objects without explicit permission.<br><br>"
    "<b>An overlap is judged by width, not by area</b>. A strip as wide as the "
    "tolerance and tens of metres long collects a hundred square units while "
    "remaining a consequence of vertex movement rather than a dispute over "
    "area.<br><br>"
    "<b>Guarantees</b>. No vertex moves further than the tolerance. An edit "
    "that takes more than a quarter of an object's area is cancelled. A repeat "
    "run over the result changes nothing.<br><br>"
    "<b>Z values</b> are restored from the nearest original vertex, because "
    "intersection operations work in plan.<br><br>"
    "The output layer is always of multi type: a repair may split an object "
    "into several parts.<br><br>"
    "Before running it, it is worth running <b>1.01</b> and seeing how many "
    "violations fall into the category left to the operator."
),

"topologyclean": (
    "<b>1.03 Topology snapping of a layer</b><br><br>"
    "Brings the borders of neighbouring objects to an exact match without "
    "moving geometry further than the given tolerance. Replaces the manual "
    "procedure of snapping a layer to itself with vertex insertion.<br><br>"
    "<b>Two operations</b><br><ul>"
    "<li><b>Node insertion</b>. If a vertex of one object lies on the edge "
    "of another but there is no node there, a node is inserted. Existing "
    "vertices stay in place. Nodes are also inserted where edges cross each "
    "other without shared vertices.</li>"
    "<li><b>Vertex merging</b>. Vertices closer to each other than the "
    "tolerance are brought to a single point. The traversal order decides "
    "which attracts which: the cluster leader does not move.</li></ul>"
    "<b>Guarantee</b>. No vertex moves further than the tolerance. Clustering "
    "is greedy by leader, so chains of vertices dragging geometry beyond the "
    "tolerance cannot appear.<br><br>"
    "<b>Objects narrower than the tolerance</b> would collapse into themselves "
    "during merging, as their opposite banks would stick together. By default "
    "such objects stay untouched and serve as an anchor for their "
    "neighbours.<br><br>"
    "<b>The reference layer</b> (optional). Its vertices are considered fixed "
    "and attract the input layer. The reference itself is not modified and does "
    "not appear in the result.<br><br>"
    "<b>Z values</b> are preserved. When merging, a vertex takes the plan "
    "coordinates of the leader and keeps its own elevation.<br><br>"
    "A repeat run over a finished result changes nothing."
),

"assemblycheck": (
    "<b>1.04 Assembly check by attribute</b><br><br>"
    "Checks whether each group of objects assembles into one whole body. "
    "The union of objects sharing an attribute value must produce exactly "
    "one part without interior rings.<br><br>"
    "<b>Why this is needed</b>. Correct assembly of blocks and panels is "
    "exactly what the coverage is being cleaned for. The check answers that "
    "final question directly, instead of a manual union without attributes "
    "followed by staring at the result.<br><br>"
    "<b>What is found</b><br><ul>"
    "<li><b>The group split into parts</b>. A break remains inside the group. "
    "The <b>note</b> field gives the distance to the nearest part: that is "
    "exactly the tolerance that was missing.</li>"
    "<li><b>An interior ring within a group</b>. A hole remains inside the "
    "group. Genuine technological cavities land here too, and are told apart "
    "by area.</li></ul>"
    "<b>An important property</b>. The check finds what a coverage-wide gap "
    "search cannot see. A gap reaching the outer edge is not a hole in the "
    "union, yet it cuts the group in two during assembly.<br><br>"
    "<b>When a group need not be whole</b>. One attribute value often describes "
    "several separated bodies: contour polygons of one level, areas of one "
    "type, islands. For such data set the <b>maximum gap</b>: parts further "
    "apart than that are treated as legitimately separate bodies. The sign that "
    "the threshold is needed shows at once: if the note field holds hundreds "
    "of metres, these are not assembly defects.<br><br>"
    "If several fields are selected, their combination becomes the key."
),

"insertnodes": (
    "<b>1.05 Insertion of missing nodes</b><br><br>"
    "Adds nodes where a vertex of one object lies on the edge of another but "
    "no node is present. The tool does nothing else: existing vertices are "
    "neither moved nor deleted.<br><br>"
    "<b>When this is needed</b>. The borders of neighbours coincide "
    "geometrically while their vertices differ. This does not affect rendering "
    "and is invisible to the eye, but it breaks dissolve by attribute, "
    "overlays, generalisation and loading into a database with strict topology. "
    "A typical source is independent construction of polygons on either side "
    "of a shared straight line, such as a fault line or the edge of a clipping "
    "mask.<br><br>"
    "<b>Guarantee</b>. A node is placed at the projection of the point onto "
    "the edge, that is strictly on the line of that edge. The shape therefore "
    "does not change at all and a self-intersection has nowhere to come from. "
    "The report prints the area before and after: a discrepancy is possible "
    "only at the level of coordinate precision.<br><br>"
    "<b>Several passes may be required</b>: an inserted node sometimes lands "
    "on the edge of a third object. The tool repeats passes while nodes are "
    "still found, and prints their number.<br><br>"
    "<b>The donor layer</b> (optional). Its vertices serve as a source of nodes "
    "for the input layer. It is not modified and does not appear in the "
    "result.<br><br>"
    "<b>The deviation from the edge</b> is not a tolerance in the usual sense. "
    "Here the distance is zero, and the number is needed only as a safeguard. "
    "The default matches coordinate precision, not object size. It should not "
    "be raised to metres: the tool would start pulling edges and the promise "
    "about area would stop holding.<br><br>"
    "These places are found by tool <b>1.01</b>, violation type <b>vertex lies "
    "on a neighbour edge without a node</b>."
),

"topologysimplify": (
    "<b>2.01 Simplification preserving shared borders</b><br><br>"
    "Thins out vertices so that a border shared by two neighbours stays "
    "shared.<br><br>"
    "<b>Why this is needed</b>. Ordinary simplification processes each polygon "
    "separately, so the same border is thinned twice and differently: where "
    "there was one line, gaps and overlaps appear. On a zone layer of 341 "
    "objects, independent simplification with a tolerance of 5 produced "
    "46 overlaps and 25 gaps, while the topological one produces none.<br><br>"
    "<b>How it works</b><br><ul>"
    "<li>Rings are broken into edges, and an edge is identified by its pair "
    "of ends regardless of direction. The same edge of two neighbours "
    "therefore yields a single record.</li>"
    "<li>Edges are glued into arcs. An arc breaks where three polygons meet "
    "or where the set of border owners changes.</li>"
    "<li>Each arc is thinned exactly once, and both neighbours receive the "
    "same result.</li>"
    "<li>Arc ends are fixed, so the nodes where three polygons meet stay "
    "in place.</li></ul>"
    "<b>The tolerance</b> sets the maximum deviation of the simplified line "
    "from the original, as in the Douglas-Peucker method.<br><br>"
    "<b>The precision for matching shared vertices</b> is not a simplification "
    "tolerance. It is needed when neighbours are stored with different "
    "coordinate precision.<br><br>"
    "The area changes during simplification, that is its purpose. Topology "
    "is not damaged: check the result with tool <b>1.01</b>, the number "
    "of findings must not grow."
),

}
